#!/usr/bin/env python3
"""Build-time only: bakes the splash PNG into a generated C header of raw
RGBA bytes, so the compiled loader never links an image-decoding library
at runtime. See claude-blocks/python-qt-startup-splash.claude.md
("Asset handling") and docs/comments-details.md [95]. Not part of the
`clientdeck` package or its runtime dependencies — run by
src/loader/Makefile only.
"""

from __future__ import annotations

import sys
from pathlib import Path

from PySide6.QtGui import QImage


def _raw_rgba_bytes(image: QImage) -> bytes:
    ptr = image.constBits()
    # sip.voidptr (needs explicit size) vs. memoryview (already sized) — see [96].
    if hasattr(ptr, "setsize"):
        ptr.setsize(image.sizeInBytes())
    return bytes(ptr)


def generate(png_path: Path, header_path: Path) -> None:
    image = QImage(str(png_path))
    if image.isNull():
        raise SystemExit(f"gen_splash_header: failed to load {png_path}")
    image = image.convertToFormat(QImage.Format.Format_RGBA8888)
    width, height = image.width(), image.height()

    raw = _raw_rgba_bytes(image)
    bytes_per_line = image.bytesPerLine()
    row_size = width * 4
    # Copies row-by-row rather than using `raw` directly — see [97].
    pixels = bytearray(row_size * height)
    for y in range(height):
        start = y * bytes_per_line
        pixels[y * row_size:(y + 1) * row_size] = raw[start:start + row_size]

    header_lines = [
        "// Generated by gen_splash_header.py — do not edit, do not commit.",
        "#pragma once",
        f"#define SPLASH_IMAGE_WIDTH {width}",
        f"#define SPLASH_IMAGE_HEIGHT {height}",
        "static const unsigned char splash_image_rgba[SPLASH_IMAGE_WIDTH * SPLASH_IMAGE_HEIGHT * 4] = {",
        ",".join(str(b) for b in pixels),
        "};",
        "",
    ]
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text("\n".join(header_lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if len(args) != 2:
        print("usage: gen_splash_header.py <input.png> <output.h>", file=sys.stderr)
        return 2
    generate(Path(args[0]), Path(args[1]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
